# Generated by Django 3.2.4 on 2021-06-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='role',
            field=models.CharField(choices=[('faculty', 'faculty'), ('student', 'student')], max_length=20, null=True),
        ),
    ]
