# Generated by Django 3.2.4 on 2021-06-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_signup_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploadingdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
