# Generated by Django 3.2.4 on 2021-06-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210627_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(choices=[('Fundamentals of Computer Programming', 'Fundamentals of Computer Programming'), ('Data Structures', 'Data Structures'), ('Computer Networks', 'Computer Networks'), ('Object Oriented Programming', 'Object Oriented Programming'), ('Design and Analysis of Algorithms', 'Design and Analysis of Algorithms'), ('Mineral Processing', 'Mineral Processing'), ('Iron and Steel Making', 'Iron and Steel Making')], max_length=50),
        ),
    ]
